name: rh_host
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0

dependencies:
  advanced_salomon_bottom_bar: ^3.3.4
  badges: ^3.1.2
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  chewie: ^1.7.5
  cloud_firestore: ^4.16.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_carousel_slider_plus: ^0.0.1
  flutter_getit: ^3.0.1
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  fake_cloud_firestore: ^2.5.1
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash/logo.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
