name: rh_host
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  advanced_salomon_bottom_bar: ^3.3.4
  badges: ^3.1.2
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  chewie: ^1.7.5
  clock: ^1.1.1
  cloud_firestore: ^5.5.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_performance: ^0.10.0+11
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_carousel_slider_plus: ^0.0.1
  flutter_getit: ^3.0.1
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  hugeicons: ^0.0.7
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  lottie: ^3.3.0
  package_info_plus: ^8.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  synchronized: ^3.3.0+3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  firebase_storage_mocks: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  import_sorter: ^4.6.0
  mocktail: ^1.0.3
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0

# FlutterGen configuration
flutter_gen:
  output: lib/core/gen/ # Generated files output directory
  line_length: 80

  # Enable integrations for the packages you're using
  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: dot-delimiter
    exclude: []

  fonts:
    enabled: true
    outputs:
      package_parameter_enabled: true

  colors:
    enabled: true
    outputs:
      package_parameter_enabled: true
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    # App Assets
    - assets/splash/
    - assets/animations/
    - assets/animations/light/
    - assets/animations/dark/
    - assets/images/
    - assets/icons/
    - assets/lottie/

    # Fonts