// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmiyG0JPg-qdeM3UU7f8HmeYRk8aUKts',
    appId: '1:644855396750:web:99b46d3604d4df1023ccdf',
    messagingSenderId: '644855396750',
    projectId: 'rh-library',
    authDomain: 'rh-library.firebaseapp.com',
    databaseURL: 'https://rh-library-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rh-library.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuCxTyGuNn9Jyk54244QsnCEXhoVmIOWI',
    appId: '1:644855396750:android:0a9041328a0414af23ccdf',
    messagingSenderId: '644855396750',
    projectId: 'rh-library',
    databaseURL: 'https://rh-library-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rh-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFvSABiL4mxx9HVox6tmyzb5b09xHHYY',
    appId: '1:644855396750:ios:d9abbd1e63c6542023ccdf',
    messagingSenderId: '644855396750',
    projectId: 'rh-library',
    databaseURL: 'https://rh-library-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rh-library.appspot.com',
    androidClientId: '644855396750-f2t5rfv1sp2rki3l23nj3216rbctus6m.apps.googleusercontent.com',
    iosClientId: '644855396750-9eqg2vn17i2ciqkl4hp3onv4acbakd7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhHost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFvSABiL4mxx9HVox6tmyzb5b09xHHYY',
    appId: '1:644855396750:ios:d9abbd1e63c6542023ccdf',
    messagingSenderId: '644855396750',
    projectId: 'rh-library',
    databaseURL: 'https://rh-library-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rh-library.appspot.com',
    androidClientId: '644855396750-f2t5rfv1sp2rki3l23nj3216rbctus6m.apps.googleusercontent.com',
    iosClientId: '644855396750-9eqg2vn17i2ciqkl4hp3onv4acbakd7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhHost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtmiyG0JPg-qdeM3UU7f8HmeYRk8aUKts',
    appId: '1:644855396750:web:97ed043de01e00a423ccdf',
    messagingSenderId: '644855396750',
    projectId: 'rh-library',
    authDomain: 'rh-library.firebaseapp.com',
    databaseURL: 'https://rh-library-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rh-library.appspot.com',
  );

}